[v0.33] Rename prisma datasource in schema.prisma code example
redwoodjs/learn.redwoodjs.com pull request #107
Opened 2021-05-16 22:23 UTC by thedavidprice

Doc changes related to redwoodjs/redwood#1941

Added to list of Docs to merge with v0.33 release.

@clairefro This is a reference code change update, which in this PR I made across all 4 translations. Ok to handle this way?

2021-05-16 23:16 UTC, clairefro commented
great! please only edit the source language docs (English), it will confuse crowdin

Once the English is merged it will trigger a translation update in the locales in crowdin. I'll take it from there

2021-05-16 23:19 UTC, clairefro requested changes

2021-05-16 23:19 UTC, clairefro commented on i18n/es/docusaurus-plugin-content-docs/current/tutorial/getting-dynamic.md
> +datasource db {
please keep original in localized docs - doc update will be handled via crowdin

2021-05-16 23:19 UTC, clairefro commented on i18n/fr/docusaurus-plugin-content-docs/current/tutorial/getting-dynamic.md
> +datasource db {
please keep original in localized docs - doc update will be handled via crowdin

2021-05-17 15:52 UTC, thedavidprice commented on i18n/es/docusaurus-plugin-content-docs/current/tutorial/getting-dynamic.md
> +datasource db {
```suggestion
datasource DS {
```

2021-05-17 15:52 UTC, thedavidprice commented on i18n/fr/docusaurus-plugin-content-docs/current/tutorial/getting-dynamic.md
> +datasource db {
```suggestion
datasource DS {
```

2021-05-17 15:54 UTC, thedavidprice commented on docs/tutorial2/adding-comments-to-the-schema.md
>  Okay, our comments service is feeling pretty solid now that we have our tests in place. The last step is add a form so that users can actually leave a comment on a blog post.
```suggestion
Okay, our comments service is feeling pretty solid now that we have our tests in place. The last step is add a form so that users can actually leave a comment on a blog post.

```

2021-05-17 15:54 UTC, thedavidprice commented on i18n/es/docusaurus-plugin-content-docs/current/tutorial/getting-dynamic.md
>  Oh muchacho, nuestra primera página con datos y ya tenemos que preocuparnos por cargar estados, errores, páginas en blanco...o ¿no?
```suggestion
Oh muchacho, nuestra primera página con datos y ya tenemos que preocuparnos por cargar estados, errores, páginas en blanco...o ¿no?

```

2021-05-17 15:55 UTC, thedavidprice commented on i18n/fr/docusaurus-plugin-content-docs/current/tutorial/getting-dynamic.md
>  notre première page avec des données et il semble que nous ayons déjà à nous soucier du chargement des états, des erreurs…
```suggestion
notre première page avec des données et il semble que nous ayons déjà à nous soucier du chargement des états, des erreurs…

```

2021-05-18 01:01 UTC, clairefro approved these changes

2021-05-18 01:01 UTC, merged