Chore/link to docs
redwoodjs/learn.redwoodjs.com pull request #14
Opened 2021-01-10 04:51 UTC by mbush92

Updated the README with a link to the official Docusaurus V2 docs now that they have been published.

https://v2.docusaurus.io/docs/next/

2021-01-11 01:44 UTC, clairefro requested changes
Thanks for the proactive edit. Actually the late-stage alpha release without documentation was meant to refer to the fact Docusaurus has not yet released documentation for i18n (the documentation is about to be released - a beta can be found in [this PR](https://github.com/facebook/docusaurus/pull/4014). Once published i18n docs will be included in the page you linked) 

But it is helpful to include the existing Docusuarus v2 docs so let's go ahead!

2021-01-11 01:44 UTC, clairefro commented on README.md
> +We are using a late stage Aplpha release of Docusuraus 2 that includes integration with l10n management service Crowdin. The docs for V2 of Docusaurus can be found [here](https://v2.docusaurus.io/doc
```suggestion
We are using a late stage Alpha release of Docusuraus 2 that includes experimental integration with l10n management service Crowdin. The docs for V2 of Docusaurus can be found [here](https://v2.docusaurus.io/docs/next/), we also have [this PR](https://github.com/facebook/docusaurus/pull/3325) and [this explanatory comment](https://github.com/facebook/docusaurus/issues/3317#issuecomment-742589241) to reference
```

2021-01-11 16:23 UTC, mbush92 commented on README.md
> +We are using a late stage Aplpha release of Docusuraus 2 that includes integration with l10n management service Crowdin. The docs for V2 of Docusaurus can be found [here](https://v2.docusaurus.io/doc
Thanks, I like that and have made the change.

2021-01-14 14:49 UTC, mbush92 commented
@clairefro when you get a chance, I made the requested changes and pushed them up.

2021-01-17 22:15 UTC, clairefro approved these changes

2021-01-17 22:15 UTC, merged