Update prerequisites.md
redwoodjs/learn.redwoodjs.com pull request #166
Opened 2021-11-30 18:59 UTC by JamesHighsmith

2021-11-30 19:13 UTC, thedavidprice requested changes

2021-11-30 19:13 UTC, thedavidprice commented on docs/tutorial/prerequisites.md
> +- node: ">=14.17 <=17.x"
```suggestion
- node: ">=14.17 <=16.x"
```

We don't officially support odd-numbered Node.js versions. They never become LTS and are intentionally short-lived.

The latest version of Redwood _did_ bump the minimum version to v14.17 ('cause Jest sub-dependency 🤷‍♂️).

https://nodejs.org/en/about/releases/

2021-11-30 20:04 UTC, clairefro commented on docs/tutorial/prerequisites.md
> +- node: ">=14.17 <=17.x"
TIL

2022-02-05 16:30 UTC, virtuoushub commented on docs/tutorial/prerequisites.md
>  - yarn: ">=1.15"
Since we are here, I ran into an issue where the tooling failed using a yarn version 2 or over.

```
$ yarn create redwood-app ./redwoodblog
...
Error: yarn >=1.15.0 <2.0.0 required, but you have 3.1.1
...
```

```suggestion
- yarn: ">=1.15 <2.x"
```
---

Probably out of scope for these changes; but we might also want to add a note where if someone is on yarn 2+, they'll want to run something like `yarn set version 1.22.17`

2022-02-07 20:07 UTC, thedavidprice commented on docs/tutorial/prerequisites.md
>  - yarn: ">=1.15"
Interesting. What I'm guessing happened here is that you were already in a directory with a yarn config that set v3. Can you confirm?

There's a (small) chance we'll be able to use yarn 3 for projects by the time we reach v1. Definitely want to keep your experience in mind as something we might need to handle either way before v1 launch.

2022-02-09 15:22 UTC, virtuoushub commented on docs/tutorial/prerequisites.md
>  - yarn: ">=1.15"
@thedavidprice correct, yarn 3 was on the path. 
```sh
yarn --version
3.1.1
```
The work around was to run `yarn set version 1.22.17` (latest 1.x version at the time of running that command) - then `yarn create redwood-app ./redwoodblog` worked as expected.

2022-02-20 18:35 UTC, cannikin commented
I've updated the versions in the prerequisite docs along with the other v1.0 updates. I didn't mess with the Yarn version.
https://learn.redwoodjs.com/docs/tutorial/prerequisites#nodejs-and-yarn-versions

2022-02-20 18:35 UTC, closed without merging