readme fixes
redwoodjs/learn.redwoodjs.com pull request #199
Opened 2022-02-24 00:36 UTC by ROZBEH

- Fixing a minor typo.
- Fixing the export for `Routes.js`
- Adding `@requireAuth` to the queries inside `posts.sdl.js`. It would throw an error without these params set.

2022-03-10 19:01 UTC, cannikin requested changes
The routing and side quest changes are good, thanks! I don't think that change the Cell doc is correct though, see my comment attached to that line. Thanks!

2022-03-11 14:54 UTC, ROZBEH commented on docs/tutorial/cells.md
> +This command will result in a new file at `/web/src/components/ArticlesCell/ArticlesCell.js` (and `test.js` `mock.js` and `stories.js` files—more on those in [part 2](/docs/tutorial2/welcome-to-redwo
Thanks Rob. How did I made this mistake :-) ?
Fixed and pushed.

2022-03-11 20:28 UTC, cannikin approved these changes

2022-03-11 20:28 UTC, merged

2022-03-11 20:28 UTC, cannikin commented
Thank you!!