French translation for footer #32
redwoodjs/learn.redwoodjs.com pull request #36
Opened 2021-01-22 16:36 UTC by ShrillShrestha

I did the french translation for the footer. Can you review it? If there are any queries, free free to mention them.

2021-01-22 19:20 UTC, M0nica commented
I took a peek at your changes and noticed the footer color in light mode is different in your staging site than the production version of site. I am assuming that was an intentional side effect. 

The top screenshot is what I see in light mode for the footer in the staging server (https://deploy-preview-36--learn-redwood.netlify.app/docs/tutorial/prerequisites/):
![Screen Shot 2021-01-22 at 2 19 08 PM](https://user-images.githubusercontent.com/6998954/105535400-d7db1b80-5cbc-11eb-9765-61c3b61ed2d4.png)

Whereas what I see in light mode for the footer for the production site (https://learn-redwood.netlify.app/docs/tutorial/welcome-to-redwood) is: 
![Screen Shot 2021-01-22 at 2 19 00 PM](https://user-images.githubusercontent.com/6998954/105535401-d7db1b80-5cbc-11eb-976b-f6ec56d82d02.png)

2021-01-22 20:17 UTC, ShrillShrestha commented
@M0nica, can you check once more? If it's still showing the same issue can you give me some idea to solve it. I haven't change any format files for the project. I just added the JSON files needed for the translations.

2021-01-22 23:17 UTC, M0nica commented
> @M0nica, can you check once more? If it's still showing the same issue, can you give me some idea to solve it? I haven't change any format files for the project. I just added the JSON files needed for the translations. Also, when I ran it in the localhost it is working fine.

Actually, I found out (based on the convo here: https://github.com/redwoodjs/learn.redwoodjs.com/issues/38#issuecomment-765701029)  that the footer color changes are related to a pre-existing strange styling issue that are currently happening in the repo with certain environments 🤔  I see the same footer styling issue on another staging site as well https://deploy-preview-33--learn-redwood.netlify.app/docs/tutorial/welcome-to-redwood.

2021-01-22 23:37 UTC, ShrillShrestha commented
@M0nica, thanks for the information. So, should I create a new pull request once the issue is fixed?

2021-01-22 23:48 UTC, M0nica commented
> @M0nica, thanks for the information. So, should I create a new pull request once the issue is fixed?

I don’t think that waiting for the issue to be resolved is necessary in this case.

2021-01-24 17:52 UTC, clairefro requested changes
Like @M0nica mentioned, don't worry about the css problem - that is a separate issue to tackle :) 

This works fantastically! Thanks for pioneering this. 

Let's keep "Discourse" in French (just like we do Twitter, Discord etc))

2021-01-24 17:52 UTC, clairefro commented on i18n/fr/docusaurus-theme-classic/footer.json
> +    "message": "Discours",
Let's keep the translation as "Discourse" since it is a proper noun
```suggestion
    "message": "Discourse",
```

2021-01-24 18:01 UTC, ShrillShrestha commented
@clairefro, do you want me to translate `Learn RedwoodJS` to `Apprendre RedwoodJS` for the navbar as well. Since that the only translation needed for the navbar.

2021-01-24 18:29 UTC, clairefro commented
> do you want me to translate `Learn RedwoodJS` to `Apprendre RedwoodJS` for the navbar

Great question - I also went back and forth on this since it is the "site title". But now I am thinking YES, as it is more welcoming to those who land on the site. 

So go ahead!

2021-01-24 18:49 UTC, ShrillShrestha commented
I made the changes.

2021-01-24 18:49 UTC, clairefro approved these changes

2021-01-24 18:55 UTC, clairefro commented
something funky seems to be going on with the Netlify checks - I'll look into it so we can merge this

2021-01-24 19:03 UTC, merged

2021-01-24 19:08 UTC, ShrillShrestha commented
Thank you, @clairefro and @M0nica. I got to learn something new. :)